apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
data:
  RABBITMQ__HOST: "rabbitmq"
  RABBITMQ__VIRTUALHOST: "/"
  ACCEPT_EULA: "Y"
  Jwt__Issuer: "FCG.Catalog.Api"
  Jwt__Audience: "FCG.Catalog.Client"
